esphome:
  name: esphome-multisensor-v1 
  friendly_name: ESPHome sense

# https://esphome.io/components/display/index.html?highlight=pages#images
font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 14
# https://fonts.google.com/icons
  - file: 'gfonts://Material+Symbols+Outlined'
    id: material_icon
    size: 14
    glyphs:
      - "\U0000e798" # water drop
      - "\U0000e1ff" # thermometer
      - "\U0000e3ab" # brightness 6

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Pinout - https://lastminuteengineers.com/esp32-pinout-reference/
# sensor - https://esphome.io/components/sensor/#sensor-filters
sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "Living Room Temperature"
      unit_of_measurement: "°C"
      id: "lr_temp"
    humidity:
      name: "Living Room Humidity"
      id: "lr_humidity"
    update_interval: 30s
    id: "sense_lr"
    
    # LDR Light Sensor
  - platform: adc
    pin: GPIO34
    name: "Living Room Brightness"
    id: "lr_bright"
    update_interval: 10s
    icon: "mdi:brightness-6"
    unit_of_measurement: "%"
    filters:
      - multiply: -100
      - offset: 101.5
i2c:
  sda: GPIO21
  scl: GPIO22
# https://esphome.io/components/display/ssd1306.html
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(material_icon), TextAlign::TOP_LEFT, "\U0000e1ff" );
      it.printf(20, 0, id(roboto), "Temp: %.1f °C", id(lr_temp).state);
      it.printf(0, 22, id(material_icon), TextAlign::TOP_LEFT, "\U0000e798" );
      it.printf(20, 22, id(roboto), "Humidity: %.1f %%", id(lr_humidity).state);
      it.printf(0, 44, id(material_icon), TextAlign::TOP_LEFT, "\U0000e3ab" );
      it.printf(20, 44, id(roboto), "Bright: %.2f %%", id(lr_bright).state);

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<redacted>" # esphome auto generates it for you

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Multisensor-V1"
    password: "<redacted>" # esphome auto generates it for you

captive_portal:
    